### ISSUE TITLE
Add cached crate wasm-gc

### ISSUE THREAD

**Issue by CryZe** [actions-rs/tool-cache#2]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions? If not, use GitHub Community forum to ask questions about Actions in a whole: https://github.community
 * [x] Does this crate helps with the Rust CI?
 * [x] Is it popular enough to be used by many users?

## Crate

**crates.io**: https://crates.io/crates/wasm-gc
**repository**: https://github.com/alexcrichton/wasm-gc

## Motivation

This allows shrinking the size of your wasm files.

**Comment by svartalf** [comment]
It is [deprecated](https://github.com/alexcrichton/wasm-gc/issues/36) and it seems that  `wasm-bindgen` should be used instead, why should it be added?

**Comment by CryZe** [comment]
wasm-bindgen doesn't run wasm-gc. It still has a strong impact on wasm file size.

**Comment by CryZe** [comment]
Or actually supposedly it does. Let me check if the file size impact is actually still true.

**Comment by svartalf** [comment]
Can you elaborate on the second point in here, please? https://rustwasm.github.io/docs/book/reference/tools.html#wasm-gc--a-hrefhttpsgithubcomalexcrichtonwasm-gcrepositorya

**Comment by CryZe** [comment]
Alright, looks like wasm-opt is the only one that still greatly impacts file size. wasm-gc doesn't seem to do anything anymore after wasm-bindgen has been executed.
