### ISSUE TITLE
wasm-bindgen-cli is not correctly cached

### ISSUE THREAD

**Issue by CryZe** [actions-rs/tool-cache#4]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions? If not, use GitHub Community forum to ask questions about Actions in a whole: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

wasm-bindgen-cli installs multiples binaries. Only one, and especially the wrong one, is getting added to the tool-cache:

https://github.com/actions-rs/tool-cache/runs/578848794?check_suite_focus=true#step:5:265

## Expected behavior

Probably all of them should be added, but I'd be fine with just the actual `wasm-bindgen` tool.

**Comment by svartalf** [comment]
Fixed in 8117a75c0232c61595387c4dcae1ef3e6501ecd9 and latest [`actions-rs/install@v0.1`](https://github.com/actions-rs/install/tree/v0.1.2) release.
