### ISSUE TITLE
Add cached crate cargo-binutils

### ISSUE THREAD

**Issue by therealprof** [actions-rs/tool-cache#6]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions? If not, use GitHub Community forum to ask questions about Actions in a whole: https://github.community
 * [x] Does this crate helps with the Rust CI?
 * [x] Is it popular enough to be used by many users?

## Crate

**crates.io**: https://crates.io/crates/cargo-binutils
**repository**: https://github.com/rust-embedded/cargo-binutils/

## Motivation

cargo-binutils provides a cargo wrapper the llvm tools shipped with Rust. Those are very useful in a variety of CI scenarios, for instance it can it be used to determine the file size of a built artifact or generate a disassembly, all without having to know target dependent information (like the location of the build product or concrete filename) by utilizing the information provided by the cargo metadata. This also increases usefulness of the cargo action a bit and allows to skip the explicit build step in case the information about the artifact is more important than the artifact itself.

**Comment by svartalf** [comment]
Closed and built by d298b2810ffe5ce445b80e48ebfa510cad58f956
